services:
  changedetection:
    image: docker.io/dgtlmoon/changedetection.io:latest
    restart: unless-stopped
    environment:
      PORT: "5000"
      TZ: ${TZ}
    expose:
      - "5000"
    volumes:
      - changedetection_data:/datastore

volumes:
  changedetection_data:
