services:
  cloudflared:
    image: docker.io/cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
